/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TicTacToeView;

import GameHouse.Player;
import ViewUtama.BackButton;
import javax.swing.JButton;


/**
 *
 * @author Rifqi
 */
public class BaseTicTacToe extends BackButton  {
    
    /**
     * Creates new form TicTacToeFrame
     */
    protected JButton[][] buttons = null;
    Player player;

    public BaseTicTacToe(Player player) {
        initComponents();
        this.player = player;
    }      
    
    protected void setTitleAndInfo(String title, String info){
        lblTitle.setText(title);
        lblInfo.setText(info);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 126, 113));
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 123, 113));
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 123, 110));
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 126, 113));
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 123, 113));
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 123, 110));
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 126, 113));
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 123, 113));
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 123, 110));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        jLabel1.setText("Tic Tac Toe");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 280, 70));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel4.setText("PLAYER 1: X");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel5.setText("INFORMASi");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, -1, -1));

        lblTitle.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("<<title>>");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 160, 40));

        lblInfo.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        lblInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo.setText("<<INFO>>");
        getContentPane().add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, 120, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/background_new.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BaseTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BaseTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BaseTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BaseTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BaseTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BaseTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BaseTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BaseTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btn1;
    protected javax.swing.JButton btn2;
    protected javax.swing.JButton btn3;
    protected javax.swing.JButton btn4;
    protected javax.swing.JButton btn5;
    protected javax.swing.JButton btn6;
    protected javax.swing.JButton btn7;
    protected javax.swing.JButton btn8;
    protected javax.swing.JButton btn9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
